apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::582624460459:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-E20SZ04C00AL
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::582624460459:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-04T21:25:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "850"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d76a6ddc-6dac-4905-9e43-1018815a2b9e
